within BuildingControlLib.BuildingControl.VDI3813.Interfaces.ActuatorSignal;
connector CommandActuatorSignalDamperPositionInput
  "Input connector of CommandActuatorSignalDamperPosition"
 extends Partial.PartialInput;
 input
    BuildingControlLib.BuildingControl.VDI3813.Types.ActuatorSignal.CommandActuatorSignalDamperPosition
  commandActuatorSignalDamperPosition;
end CommandActuatorSignalDamperPositionInput;
