within BuildingControlLib.BuildingControl.VDI3813.Interfaces.ActuatorSignal;
connector CommandActuatorSignalLockValvePositionOutput
  "Output connector of CommandActuatorSignalLockValvePosition"
 extends Partial.PartialOutput;
 output
    BuildingControlLib.BuildingControl.VDI3813.Types.ActuatorSignal.CommandActuatorSignalLockValvePosition
 commandActuatorSignalLockValvePosition;
end CommandActuatorSignalLockValvePositionOutput;
