within BuildingControlLib.BuildingControl.VDI3813.Interfaces.ActuatorSignal;
connector StatusActuatorSignalLockValvePositionInput
  "Input connector of StatusActuatorSignalLockValvePosition"
 extends Partial.PartialInput;
 input
    BuildingControlLib.BuildingControl.VDI3813.Types.ActuatorSignal.StatusActuatorSignalLockValvePosition
  statusActuatorSignalLockValvePosition;
end StatusActuatorSignalLockValvePositionInput;
