within BuildingControlLib.BuildingControl.VDI3813.ApplicationFunctions.Internal;
block ShadowCorrectionFunctionality
  extends Interfaces.Partial.PartialFunctionality;
end ShadowCorrectionFunctionality;
